language: php

php:
  - '7.0'

before_script:
  - nvm install 6
  - gem install sass
  - composer install --no-interaction

before_deploy:
  - npm i
  - mkdir public/js
  - cp node_modules/bootstrap-sass/assets/javascripts/bootstrap.min.js public/js/
  - cp -R node_modules/font-awesome/fonts/ public/fonts/
  - sass ./web/Core/Assets/Styles/main.scss:public/css/style.css --sourcemap=none --style compressed --trace

deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: VcL6X31tHdTWnTqoz2xdRdmZwnyK2YtgQ/SdMWDmT39TI0WLMUoLxKtBAkmR8PL1J+nMglU82dHzA1Sw3yeO/rhaIH+xXynCpOJfUkpssiaa55LtHrUEJrk+9i0uBwmJDgSx8OSHDAF1AiIsIq4g52pqJQdymeDeiKIE28cst1yV4HvMBQe+zTxM0Avcw9ZjZEncLvobtKbHRr7+zHFRFaVh0IhYl7r9oV+Jjwm0jA7ThBzot/zTz8hYPprtzmbzdQn2x7xYTLmINeDjOfZZaG4VySZgFDFjfzD/YscbCErAMXgnk9xil6IOglpRuv5Nh+LpP/bOdHB/lejkZXtWJfZRBfo8NmUmDDtXyt2iXxrRp7IME/OaQGdESsSOGvDUWjAylnONhgTo4K2E5IVUPYHJgcDglZWf53SZOlELSyc8k7Z6a1MSgsSEOWq6q94/O8IFNi1b0KlYHXpJgtHHf/wVWUn5s6iQR07fPQXH3bGQQAGc12m7aIHBl3RkOpanGd+jNEbr+SOqhsx5dChU/1hnLd8e6TvUm7YdgfV+tQXqXexU6rnF0J2ijS8E1o4oZM8qy9XDE6yiY/g9md1hZBt5kgOIocUI7wmSiW6xSQG1Nk8utb23DMZRqajeSjZPDm/gmfduZ7I0SsNNvH+3DeVtDoLgkJi+f1hKVCYQbrE=
  app: phpwarks-site
  on:
    repo: phpwarks/website
notifications:
  slack:
    secure: jI+dusDE/cWNekZkAaBk36YUqQpSMW8QLVRmYL7+TKsBykG8f228MuS/ar/HkFi37Ux73fNQjd8Xr8bs/1TBgVBgKJ7IATNaBl4k6BULnUy9WdZc9ETtthhMkGc5vJ4HY3MLNpHQRI7PHkvsXB9oroGs5nhWsP0/aUqt3kOhE7Ku8czKDL/syMVgSH7uy62v0CQTlIMWkRi2errCe/7PIzyNLjerL8pg5Jy5acHambFr252c/TfF4J7O8qhyE4oCYi2PlxaWMZ4+NVKOmxx8jUJZKSp/Y5LS5KnWiwbMb/pzCNsEpmQI6CmK5RmZRcJKMCN3MBM000AmTZUvgR+3dcxslDqJPvRc5zqLb6PciXqQ2DWWkNDHGKVVRBSOLxefNzVTInyRGZwexIxtZVL/HC5eU4DfcQ1WH+6vDC29gCkkxLemlf6yGaX682Le8aLOUcJ3xeyr/EjosdM5kESNNlcj9BfsYnsb/n9WRXnOXoRkPi8//pC+iqStxyMSA0UajO1xCuPtUzZ6Tz2R64EZr22cQOGG3/zpNnRslhAXJaR2xqxKt67aDaYhcmIlsmqco1d91+wWG8QNk/T3QPkLLaYnd5qv9Q7NkfU50q0NjceT7m5xlz2YsMX1uXCVjEA+j2BWZf1/sxoY8MS6w8TVDcpqiTy6ymuPizL/Zg76x+g=
