version: "2"

services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/phpwarks
            - ./.provisioning/nginx/phpwarks.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        image: php:fpm
        volumes:
            - ./:/var/www/phpwarks
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
