- name: Setup Nginx base configuration
  sudo: true
  template: src=nginx.conf.tpl dest=/etc/nginx/nginx.conf
  tags:
    - nginx

- name: Setup phpwarks specific configuration
  sudo: true
  template: src=phpwarks.vh.tpl dest=/etc/nginx/sites-enabled/phpwarks
  tags:
    - nginx